CREATE DATABASE IF NOT EXISTS `springbootdb`;
USE `springbootdb`;

DROP TABLE IF EXISTS `product`;

CREATE TABLE `product` (
	`id` int NOT NULL AUTO_INCREMENT PRIMARY KEY,
	`version` VARCHAR(512) DEFAULT NULL,
	`name` VARCHAR(512) DEFAULT NULL,
	`price` INT DEFAULT NULL,
	`product_id` VARCHAR(255) DEFAULT NULL
) AUTO_INCREMENT = 10;
